echo Making build dir...
mkdir build
cd build
echo Running cmake...
cmake ..
echo building...
make "$@"
echo build complete
./server.wt --http-address=0.0.0.0 --http-port=8080 --deploy-path=/hello --docroot=../src/docroot/
